const { expect } = require('@jest/globals')
const diffArray = require('./diff-two-arrays')

test('returns the symmetric difference of the two arrays', () => {
    expect(diffArray([1, 2, 3, 5], [1, 2, 3, 4, 5])).toBe([4])
    expect(diffArray([1, 2, 3, 5], [1, 2, 3, 4, 5])).toEqual(array)
    expect(diffArray([1, 2, 3, 5], [1, 2, 3, 4, 5])).toHaveLength(1)
    expect(diffArray(["diorite", "andesite", "grass", "dirt", "pink wool", "dead shrub"], ["diorite", "andesite", "grass", "dirt", "dead shrub"])).toBe(["pink wool"])
    expect(diffArray(["diorite", "andesite", "grass", "dirt", "pink wool", "dead shrub"], ["diorite", "andesite", "grass", "dirt", "dead shrub"])).toHaveLength(1)
    expect(diffArray(["andesite", "grass", "dirt", "pink wool", "dead shrub"], ["diorite", "andesite", "grass", "dirt", "dead shrub"])).toBe(["diorite", "pink wool"])
    expect(diffArray(["andesite", "grass", "dirt", "pink wool", "dead shrub"], ["diorite", "andesite", "grass", "dirt", "dead shrub"])).toHaveLength(2)
    expect(diffArray(["andesite", "grass", "dirt", "dead shrub"], ["andesite", "grass", "dirt", "dead shrub"])).toEqual(array)
    expect(diffArray(["andesite", "grass", "dirt", "dead shrub"], ["andesite", "grass", "dirt", "dead shrub"])).toHaveLength(0)
    expect(diffArray([1, "calf", 3, "piglet"], [1, "calf", 3, 4])).toBe(["piglet", 4])
    expect(diffArray([1, "calf", 3, "piglet"], [1, "calf", 3, 4])).toEqual(array)
    expect(diffArray([1, "calf", 3, "piglet"], [1, "calf", 3, 4])).toHaveLength(2)
    expect(diffArray([], ["snuffleupagus", "cookie monster", "elmo"])).toBe(["snuffleupagus", "cookie monster", "elmo"])
    expect(diffArray([], ["snuffleupagus", "cookie monster", "elmo"])).toEqual(array)
    expect(diffArray([], ["snuffleupagus", "cookie monster", "elmo"])).toHaveLength(3)
    expect(diffArray([1, "calf", 3, "piglet"], [7, "filly"])).toBe([1, "calf", 3, "piglet", 7, "filly"])
    expect(diffArray([1, "calf", 3, "piglet"], [7, "filly"])).toEqual(array)
    expect(diffArray([1, "calf", 3, "piglet"], [7, "filly"])).toHaveLength(6)
})